In [1]:
from pythtb import Lattice
import numpy as np

In [2]:
lat_vecs = [[1, 0], [1 / 2, np.sqrt(3) / 2]]
orb_vecs = [[1 / 3, 1 / 3], [2 / 3, 2 / 3]]

In [3]:
lat = Lattice(orb_vecs=orb_vecs, lat_vecs=lat_vecs, periodic_dirs=[0, 1])

In [4]:
print(lat)

----------------------------------------
       Lattice structure report         
----------------------------------------
r-space dimension           = 2
k-space dimension           = 2
periodic directions         = [0, 1]
number of orbitals          = 2

Lattice vectors (Cartesian):
  # 0 ===> [ 1.000,  0.000]
  # 1 ===> [ 0.500,  0.866]
Volume of unit cell (Cartesian) = 0.866 [A^d]

Reciprocal lattice vectors (Cartesian):
  # 0 ===> [ 6.283, -3.628]
  # 1 ===> [ 0.000,  7.255]
Volume of reciprocal unit cell = 45.586 [A^-d]

Orbital vectors (Cartesian):
  # 0 ===> [ 0.500,  0.289]
  # 1 ===> [ 1.000,  0.577]

Orbital vectors (fractional):
  # 0 ===> [ 0.333,  0.333]
  # 1 ===> [ 0.667,  0.667]
----------------------------------------


In [5]:
lat.get_orb_vecs(cartesian=True)

array([[0.5       , 0.28867513],
       [1.        , 0.57735027]])

In [6]:
print(lat.get_recip_lat_vecs())
print(lat.recip_lat_vecs)

[[ 6.28318531 -3.62759873]
 [ 0.          7.25519746]]
[[ 6.28318531 -3.62759873]
 [ 0.          7.25519746]]


In [7]:
overlap_mat = lat.lat_vecs @ lat.recip_lat_vecs.T
print(overlap_mat / (2 * np.pi))

[[ 1.00000000e+00  0.00000000e+00]
 [-4.79476621e-17  1.00000000e+00]]


In [8]:
print(lat.recip_volume, lat.cell_volume)

45.58575006211245 0.8660254037844386
